### PR TITLE
Update extension metadata

### PR DESCRIPTION
**Pull request by benja-M-1**
Hi 👋 

I have updated the metadata so that the extension looks better in the marketplace. I haven't tested it locally though, so you may want to do it first 😇

### CODE REVIEW

**Comment by benja-M-1** [comment]
Hello 👋  maybe you missed this PR. Just wanted to bump it up in your notification 🙂

**Comment by 0xE282B0** [comment]
@benja-M-1  Oh, yeah. That slipped my attention 🙈.
But with Docker's Wasm support, this plugin is obsolete anyway. Which brings me to the next question, how do I unregister a Docker extension?

**Comment by benja-M-1** [comment]
You can't do it yourself but we can do it for you.

**Comment by benja-M-1** [comment]
I am sad to see the extension go away but it makes sense!
We are waiting for your confirmation to proceed and we will remove the extension form the store.

**Comment by 0xE282B0** [comment]
At lest I tested the whole life cycle 😉
And I'm sure to submit another extension as soon as I have a good idea. 

Can I confirm here or shall I open an issue in the extensions-submission repository?

**Comment by benja-M-1** [comment]
Just confirm here I will handle the rest :)

**Comment by 0xE282B0** [comment]
Then I now officially confirm that the KWasm docker extension can be removed. 

Thanks for supporting me during the whole life cycle of this extension 😊

**Comment by Frezzle** [comment]
Hi 👋 I'm in @benja-M-1's team. We removed your extension from the marketplace, and it should soon not show there anymore. We look forward to your next one! :)

**Pull request closed without merging**
